[package]
name = "chronicle-proto"
version = "0.1.0"
edition = "2024"
resolver = "2"


[dependencies]
tonic = { workspace = true }
tonic-build = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }